name: "[Refactor] 리팩토링"
description: 새 알고리즘 문제 풀이를 위한 refactor 이슈 템플릿입니다.
title: "[Refactor] 문제 사이트 | 알고리즘 주제 | 문제 번호 | 문제 이름과 내용"
labels:
  - refactor
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ 이슈 설명
        아래 내용을 채워주세요.

  - type: input
    id: algorithm_topic
    attributes:
      label: 알고리즘 주제
      description: 어떤 알고리즘 주제와 관련된 문제인지 입력하세요. (예: 구현, DP, BFS 등)
      placeholder: 알고리즘 주제를 입력하세요.

  - type: input
    id: site_and_problem
    attributes:
      label: 문제 사이트와 번호
      description: 문제 사이트와 번호를 작성하세요. (예: 백준 14467)
      placeholder: 문제 사이트와 번호를 입력하세요.

  - type: textarea
    id: problem_description
    attributes:
      label: 문제 설명
      description: 문제의 간단한 설명을 작성하세요.
      placeholder: 문제 설명을 입력하세요.

  - type: textarea
    id: solution_idea
    attributes:
      label: 풀이 아이디어
      description: 문제를 어떻게 접근하고 풀이할 것인지 작성하세요.
      placeholder: 풀이 아이디어를 입력하세요.

  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      description: 이 문제의 우선순위를 선택하세요.
      options:
        - 높음
        - 중간
        - 낮음